In [1]:
a,b,c,d,e = [1,2,3,4,54]

mylist=[a,b,c,d,e]

mysum = long(0)
mysum = a+b+c+d+e

mins=min(mylist)
maxs=max(mylist)

max4=mysum-mins
min4=mysum-maxs

print min4,max4

10 63


In [4]:
ord('a'),ord('b')

(97, 98)

In [1]:
from collections import deque

In [13]:
ip_str=raw_input()

my_stack=deque()


11aabbcccdeecggh


In [14]:
for ch in ip_str:
    last=len(my_stack)
    if last and ch==my_stack[last-1]:
        my_stack.pop()
    else:
        my_stack.append(ch)

print my_stack

deque(['c', 'd', 'c', 'h'])


In [16]:
str=''
for ch in my_stack:
    str+=ch
print str

cdch


In [17]:
ip_str=raw_input()

beabeefeab


In [18]:
a=[1,2,3,4,54]

aa=a*2

print aa

[1, 2, 3, 4, 54, 1, 2, 3, 4, 54]


In [5]:
n=int(raw_input())
fib_arr=[0]*n
fib_arr[0]=1
fib_arr[1]=1
def fibonacci(n):
    fib_val=0
    if n<=2:
        fib_val=1
    else:
        if fib_arr[n-1]==0:
            #compute
            fib_val=fibonacci(n-1)+fibonacci(n-2)
            fib_arr[n-1]=fib_val
        else:
            fib_val=fib_arr[n-1]

    return fib_val

print fibonacci(n)

10
55


In [6]:
fib_arr

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

In [2]:
n=int(raw_input())
hac_arr=[0]*n
hac_arr[0]=1
hac_arr[1]=2
hac_arr[2]=3
def hackonacci(n):
    hac_val=0
    if n<=3:
        hac_val=hac_arr[n-1]
    else:
        if hac_arr[n-1]==0:
            #compute
            hac_val=1*hackonacci(n-1)+2*hackonacci(n-2)+3*hackonacci(n-3)
            hac_arr[n-1]=hac_val
        else:
            hac_val=hac_arr[n-1]

    return hac_val

print hackonacci(n)

256
403747940297104609874815966005939715637921288949950973705056014484981972729158056008024715229378


In [30]:
n=10
def hackonacci_rec(n):
    hac_val=0
    if n<=3:
        return n
    else:
        #compute
        return 1*hackonacci(n-1)+2*hackonacci(n-2)+3*hackonacci(n-3)

print hackonacci_rec(n)

1657


In [19]:
np.zeros(n)

array([ 0.,  0.,  0.,  0.])

In [50]:
#print hac_arr

In [3]:
n=4
hac_mat=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
hac_val_mat=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
print hac_mat

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [4]:
import numpy as np
nn=np.zeros((n, n))
print nn

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [5]:
n=4
hac_mat=np.zeros((n, n))
hac_val_mat=np.zeros((n, n))
print hac_mat

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [6]:
hac_mat[1]

array([ 0.,  0.,  0.,  0.])

In [8]:
def populate_hac_mat(n):
    for i in range(n):
        for j in range(n):
            val=hac_arr[((i+1)*(j+1))**2 -1]
            #print val
            hac_val_mat[i][j]=val
            if val%2==0:
                hac_mat[i][j]=0#'X'
            else:
                hac_mat[i][j]=1#'Y'
            #print hac_mat
populate_hac_mat(n)
print hac_mat
#print hac_val_mat

[[ 1.  0.  0.  0.]
 [ 0.  0.  1.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]]


In [11]:
rotated = np.rot90(hac_mat,-1)
print rotated

[[ 0.  0.  0.  1.]
 [ 1.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]]


In [17]:
hac_mat<>rotated

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False]], dtype=bool)

In [18]:
sum(sum(hac_mat<>rotated))

10

In [21]:
n= 5 
Matrix = [[0 for x in range(n)] for y in range(n)] 

In [22]:
Matrix

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [24]:
def rotate90(mat,n):
    ret_mat=[[float(0) for x in range(n)] for y in range(n)]
    
    for idx_row in range(n):
        row=mat[idx_row]
        for jdx_col in range(n):
            ret_mat[jdx_col][n-1-idx_row]=row[jdx_col]
    return ret_mat
print rotate90(hac_mat,4)

[[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 1.0, 0.0]]


In [27]:
rotated=rotate90(hac_mat,4)
print rotated

[[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 1.0, 0.0]]


In [28]:
hac_mat<>rotated

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False]], dtype=bool)